/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_raiffeisen_PerfPtProf */

#ifndef _Included_ru_raiffeisen_PerfPtProf
#define _Included_ru_raiffeisen_PerfPtProf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_raiffeisen_PerfPtProf
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_raiffeisen_PerfPtProf_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_raiffeisen_PerfPtProf
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_raiffeisen_PerfPtProf_start
  (JNIEnv *, jclass);

/*
 * Class:     ru_raiffeisen_PerfPtProf
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_raiffeisen_PerfPtProf_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
